### PR TITLE
Add marbl support to nmldef2html.py

### PR DESCRIPTION
**Pull request by mnlevy1981**
This isn't entirely complete, but I got the easy stuff done. There are some derived types in the MARBL settings file that need to be handled, e.g. listing `autotrophs%sname` as `dtype(3)%string` and `grazing%auto_ind` as `dtype(3,1)%integer(1)`. Actually getting that logic into the python seems pretty invasive, so I just wanted to check in and make sure the way I'm approaching changes in `nmldef2html.py` makes sense before continuing. Please don't accept this until I get the rest of the variables documented.

### CODE REVIEW

**Comment by mnlevy1981** [comment]
Actually, now that I've gotten this far, I wonder if I'd be better off using the existing MARBL python code to your dictionary. I think that would expand each element of every array, but that's okay (I hope)

**Comment by mnlevy1981** [comment]
This script works, in the sense that it generates `marbl_nml.html` without affecting the other namelist files (as far as I can tell). It's not the prettiest code, and I'm happy to help you clean it up next week... but if you're okay with this version, it would be great if we could get the MARBL html file up on the CESM 2.0 website.

**Comment by mnlevy1981** [comment]
Oh, I should add that this works with python 2.7 but I would be surprised if it was compatible with py3...

**Review by bertinia — COMMENTED** [review]
@mnlevy1981 - would you run the script for another namelist to make sure that the changes you introduced don't break any of the other nml file generation?

**Comment by mnlevy1981** [comment]
Most of the files in `/cesmweb/html/models/cesm2/component_settings/` are unchanged, and I think the files that did change are probably due to changes in the release tag?

```
$ for file in *; do echo $file; diff /cesmweb/html/models/cesm2/component_settings/$file .; echo ""; done
cam_nml.html
109c109
< 	    <h5>HTML created on: 2018-06-02</h5>
---
> 	    <h5>HTML created on: 2018-06-07</h5>
10987,10991c10987
< List of SCRIP grid filenames each representing a destination grid. If
< provided during a CAM simulation running the spectral element dycore,
< mapping files will be created from the native cubed-sphere grid to
< each destination grid. Both native mapping (using the internal
< spectral element basis functions) and bilinear maps are created.
---
> List of SCRIP grid filenames each representing a destination grid. If provided during a CAM simulation running the spectral element dycore, mapping files will be created from the native cubed-sphere grid to each destination grid. Both native mapping (using the internal spectral element basis functions) and bilinear maps are created.
12544c12540
< </html>
---
> </html>
\ No newline at end of file

cice_nml.html
109c109
< 	    <h5>HTML created on: 2018-06-02</h5>
---
> 	    <h5>HTML created on: 2018-06-07</h5>

cism_nml.html
109c109
< 	    <h5>HTML created on: 2018-06-02</h5>
---
> 	    <h5>HTML created on: 2018-06-07</h5>

clm4_0_nml.html
109c109
< 	    <h5>HTML created on: 2018-06-02</h5>
---
> 	    <h5>HTML created on: 2018-06-07</h5>
893c893
< 		  <td> 0.9x1.25 <br/> is 1.9x2.5 for: {'sitespf_pt': 'none'} <br/> is 1x1_brazil for: {'sitespf_pt': '1x1_brazil'} <br/> is 5x5_amazon for: {'sitespf_pt': '5x5_amazon'} <br/> is 1x1_camdenNJ for: {'sitespf_pt': '1x1_camdenNJ'} <br/> is 1x1_vancouverCAN for: {'sitespf_pt': '1x1_vancouverCAN'} <br/> is 1x1_mexicocityMEX for: {'sitespf_pt': '1x1_mexicocityMEX'} <br/> is 1x1_asphaltjungleNJ for: {'sitespf_pt': '1x1_asphaltjungleNJ'} <br/> is 1x1_urbanc_alpha for: {'sitespf_pt': '1x1_urbanc_alpha'} <br/> is 1x1_numaIA for: {'sitespf_pt': '1x1_numaIA'} <br/> is 1x1_smallvilleIA for: {'sitespf_pt': '1x1_smallvilleIA'} <br/></td>
---
> 		  <td> is 1.9x2.5 for: {'sitespf_pt': 'none'} <br/> is 1x1_brazil for: {'sitespf_pt': '1x1_brazil'} <br/> is 5x5_amazon for: {'sitespf_pt': '5x5_amazon'} <br/> is 1x1_camdenNJ for: {'sitespf_pt': '1x1_camdenNJ'} <br/> is 1x1_vancouverCAN for: {'sitespf_pt': '1x1_vancouverCAN'} <br/> is 1x1_mexicocityMEX for: {'sitespf_pt': '1x1_mexicocityMEX'} <br/> is 1x1_asphaltjungleNJ for: {'sitespf_pt': '1x1_asphaltjungleNJ'} <br/> is 1x1_urbanc_alpha for: {'sitespf_pt': '1x1_urbanc_alpha'} <br/> is 1x1_numaIA for: {'sitespf_pt': '1x1_numaIA'} <br/> is 1x1_smallvilleIA for: {'sitespf_pt': '1x1_smallvilleIA'} <br/> 0.9x1.25 <br/></td>

datm_nml.html
109c109
< 	    <h5>HTML created on: 2018-06-02</h5>
---
> 	    <h5>HTML created on: 2018-06-07</h5>

desp_nml.html
109c109
< 	    <h5>HTML created on: 2018-06-02</h5>
---
> 	    <h5>HTML created on: 2018-06-07</h5>

dice_nml.html
109c109
< 	    <h5>HTML created on: 2018-06-02</h5>
---
> 	    <h5>HTML created on: 2018-06-07</h5>

dlnd_nml.html
109c109
< 	    <h5>HTML created on: 2018-06-02</h5>
---
> 	    <h5>HTML created on: 2018-06-07</h5>

docn_nml.html
109c109
< 	    <h5>HTML created on: 2018-06-02</h5>
---
> 	    <h5>HTML created on: 2018-06-07</h5>

drof_nml.html
109c109
< 	    <h5>HTML created on: 2018-06-02</h5>
---
> 	    <h5>HTML created on: 2018-06-07</h5>

drv_fields_nml.html
109c109
< 	    <h5>HTML created on: 2018-06-02</h5>
---
> 	    <h5>HTML created on: 2018-06-07</h5>

drv_nml.html
109c109
< 	    <h5>HTML created on: 2018-06-02</h5>
---
> 	    <h5>HTML created on: 2018-06-07</h5>

dwav_nml.html
109c109
< 	    <h5>HTML created on: 2018-06-02</h5>
---
> 	    <h5>HTML created on: 2018-06-07</h5>

marbl_nml.html
diff: /cesmweb/html/models/cesm2/component_settings/marbl_nml.html: No such file or directory

mosart_nml.html
109c109
< 	    <h5>HTML created on: 2018-06-02</h5>
---
> 	    <h5>HTML created on: 2018-06-07</h5>

pop2_nml.html
109c109
< 	    <h5>HTML created on: 2018-06-02</h5>
---
> 	    <h5>HTML created on: 2018-06-07</h5>

rtm_nml.html
109c109
< 	    <h5>HTML created on: 2018-06-02</h5>
---
> 	    <h5>HTML created on: 2018-06-07</h5>

ww3_nml.html
109c109
< 	    <h5>HTML created on: 2018-06-02</h5>
---
> 	    <h5>HTML created on: 2018-06-07</h5>
```

**Comment by mnlevy1981** [comment]
I do get

```
Error: unable to parse file /home/mlevy/codes/CESM/cesm2.0.0ish/components/clm/bld/namelist_files/namelist_definition_clm4_5.xml
```

But I was seeing that even before I started making changes...

**Comment by bertinia** [comment]
The clm4.5 nml has a stray ">" character that makes the XML invalid. I had to edit that file and 
added an issue to the ctsm repo.

**Pull request merged**
